### ISSUE TITLE
TypeError: Cannot set property 'render' of undefined

### ISSUE THREAD

**Issue by ac88** [vuejs/rfcs#216]
### <script setup> production mode

- win10

- node v14.13.0

https://codesandbox.io/s/xenodochial-surf-jcxcl

if comment `src\views\home\index.vue`

```xml
<!--script lang="ts">
import '@/fix-setup-sugar'
</script-->
<script setup lang="ts">
export { default as Contact } from '../Contact.vue';
</script>
```

the vue-cli-service build will show

```
 error  in ./src/views/home/index.vue?vue&type=script&setup=true&lang=ts

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
Cannot read property 'content' of null
    at PoolWorker.fromErrorObj (D:\Dev\template\jcxcl\node_modules\thread-loader\dist\WorkerPool.js:262:12)
    at D:\Dev\template\jcxcl\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at mapSeries (D:\Dev\template\jcxcl\node_modules\neo-async\async.js:3625:14)
    at PoolWorker.onWorkerMessage (D:\Dev\template\jcxcl\node_modules\thread-loader\dist\WorkerPool.js:170:35)
    at D:\Dev\template\jcxcl\node_modules\thread-loader\dist\WorkerPool.js:152:14
    at Object.selectBlock (D:\Dev\template\jcxcl\node_modules\@vue\cli-service\node_modules\vue-loader-v16\dist\select.js:25:45)
    at Object.loader (D:\Dev\template\jcxcl\node_modules\@vue\cli-service\node_modules\vue-loader-v16\dist\index.js:59:25)

 @ ./src/views/home/index.vue?vue&type=script&setup=true&lang=ts 1:0-429 1:0-429 1:430-848 1:430-848
 @ ./src/views/home/index.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

Otherwise use this meaningless `script`,build can success done.but the page will show error:`TypeError: Cannot set property 'render' of undefined`

the file /js/home.6e14bc9a.js

```
(void 0).render
```

**Comment by posva** [comment]
You have to export a `default`:

```js
export { default as default } from '../Contact.vue';
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions! Also, this is the RFC repository, not vue-next

**Comment by ac88** [comment]
@posva  Could you help me fix this problem  on this link? https://codesandbox.io/s/xenodochial-surf-jcxcl 

I don't understand 

```js
export { default as default } from '../Contact.vue';
```
